[package]
name = "rust-of-life"
version = "0.1.0"
authors = ["Alexis von Glasow <ashgenesis@gmail.com>", "RÃ©mi Parpaillon <remi.parpaillon@gmail.com"]

[dependencies]
ansi_term = "0.8"
rand = "0.3.14"
